import { Routes } from '@angular/router';
import { HomeComponent } from './section/home/home.component';
import {ProgrammingComponent} from './section/programming/programming.component';
import {IFrameComponent} from './shared/iframe/iframe.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'programming', component: ProgrammingComponent},
  { path: 'programming/ut1', component: IFrameComponent },
  { path: 'programming/ut2', component: IFrameComponent },
  { path: 'programming/ut3', component: IFrameComponent },
  { path: 'programming/ut4', component: IFrameComponent },
  { path: 'programming/ut5', component: IFrameComponent },
  { path: 'programming/ut6', component: IFrameComponent },
  { path: 'programming/ut7', component: IFrameComponent },
  { path: 'programming/ut8', component: IFrameComponent },
  { path: 'programming/ut9', component: IFrameComponent },
  { path: 'programming/ut10', component: IFrameComponent },

  { path: 'computer-systems', component: ProgrammingComponent},
  { path: 'computer-systems/ut1', component: IFrameComponent },
  { path: 'computer-systems/ut2', component: IFrameComponent },
  { path: 'computer-systems/ut3', component: IFrameComponent },
  { path: 'computer-systems/ut4', component: IFrameComponent },
  { path: 'computer-systems/ut5', component: IFrameComponent },
  { path: 'computer-systems/ut6', component: IFrameComponent },
  { path: 'computer-systems/ut7', component: IFrameComponent },
  { path: 'computer-systems/ut8', component: IFrameComponent },
  { path: 'computer-systems/ut9', component: IFrameComponent },

  { path: 'databases', component: ProgrammingComponent},
  { path: 'databases/ut1', component: IFrameComponent },
  { path: 'databases/ut2', component: IFrameComponent },
  { path: 'databases/ut3', component: IFrameComponent },
  { path: 'databases/ut4', component: IFrameComponent },
  { path: 'databases/ut5', component: IFrameComponent },
  { path: 'databases/ut6', component: IFrameComponent },
  { path: 'databases/ut7', component: IFrameComponent },

  { path: 'markup-languages', component: ProgrammingComponent},
  { path: 'markup-languages/ut1', component: IFrameComponent },
  { path: 'markup-languages/ut2', component: IFrameComponent },
  { path: 'markup-languages/ut3', component: IFrameComponent },
  { path: 'markup-languages/ut4', component: IFrameComponent },
  { path: 'markup-languages/ut5', component: IFrameComponent },
  { path: 'markup-languages/ut6', component: IFrameComponent },

  { path: 'development-environments', component: ProgrammingComponent},
  { path: 'development-environments/ut1', component: IFrameComponent },
  { path: 'development-environments/ut2', component: IFrameComponent },
  { path: 'development-environments/ut3', component: IFrameComponent },
  { path: 'development-environments/ut4', component: IFrameComponent },
  { path: 'development-environments/ut5', component: IFrameComponent },

  { path: 'training-and-job-guidance', component: ProgrammingComponent},
  { path: 'training-and-job-guidance/ut1', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut2', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut3', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut4', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut5', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut6', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut7', component: IFrameComponent },
  { path: 'training-and-job-guidance/ut8', component: IFrameComponent },

  { path: 'client-side-web-development', component: ProgrammingComponent},
  { path: 'client-side-web-development/ut1', component: IFrameComponent },
  { path: 'client-side-web-development/ut2', component: IFrameComponent },
  { path: 'client-side-web-development/ut3', component: IFrameComponent },
  { path: 'client-side-web-development/ut4', component: IFrameComponent },
  { path: 'client-side-web-development/ut5', component: IFrameComponent },
  { path: 'client-side-web-development/ut6', component: IFrameComponent },

  { path: 'client-side-web-server', component: ProgrammingComponent},
  { path: 'client-side-web-server/ut1', component: IFrameComponent },
  { path: 'client-side-web-server/ut2', component: IFrameComponent },
  { path: 'client-side-web-server/ut3', component: IFrameComponent },
  { path: 'client-side-web-server/ut4', component: IFrameComponent },
  { path: 'client-side-web-server/ut5', component: IFrameComponent },
  { path: 'client-side-web-server/ut6', component: IFrameComponent },
  { path: 'client-side-web-server/ut7', component: IFrameComponent },

  { path: 'web-application-deployment', component: ProgrammingComponent},
  { path: 'web-application-deployment/ut1', component: IFrameComponent },
  { path: 'web-application-deployment/ut2', component: IFrameComponent },
  { path: 'web-application-deployment/ut3', component: IFrameComponent },
  { path: 'web-application-deployment/ut4', component: IFrameComponent },
  { path: 'web-application-deployment/ut5', component: IFrameComponent },

  { path: 'web-interface-design', component: ProgrammingComponent},
  { path: 'web-interface-design/ut1', component: IFrameComponent },
  { path: 'web-interface-design/ut2', component: IFrameComponent },
  { path: 'web-interface-design/ut3', component: IFrameComponent },
  { path: 'web-interface-design/ut4', component: IFrameComponent },
  { path: 'web-interface-design/ut5', component: IFrameComponent },
  { path: 'web-interface-design/ut6', component: IFrameComponent },
  { path: 'web-interface-design/ut7', component: IFrameComponent },
  { path: 'web-interface-design/ut8', component: IFrameComponent },
  { path: 'web-interface-design/ut9', component: IFrameComponent },
  { path: 'web-interface-design/ut10', component: IFrameComponent },

  { path: 'company-and-entrepreneurial-initiative', component: ProgrammingComponent},
  { path: 'company-and-entrepreneurial-initiative/ut1', component: IFrameComponent },
  { path: 'company-and-entrepreneurial-initiative/ut2', component: IFrameComponent },
  { path: 'company-and-entrepreneurial-initiative/ut3', component: IFrameComponent },
  { path: 'company-and-entrepreneurial-initiative/ut4', component: IFrameComponent },
  { path: 'company-and-entrepreneurial-initiative/ut5', component: IFrameComponent },
  { path: 'company-and-entrepreneurial-initiative/ut6', component: IFrameComponent },
  { path: 'company-and-entrepreneurial-initiative/ut7', component: IFrameComponent },

  { path: 'web-application-development-project', component: ProgrammingComponent},
  { path: 'web-application-development-project/ut1', component: IFrameComponent },

  { path: 'training-in-workplaces', component: ProgrammingComponent},
  { path: 'training-in-workplaces/ut1', component: IFrameComponent }

];
