import { Routes } from '@angular/router';
import { HomeComponent } from './section/home/home.component';
import {IframeContentViewComponent} from './content/application/iframe-content-view/iframe-content-view.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'programacion', component: HomeComponent },
  { path: 'programacion/ut1', component: IframeContentViewComponent },
  { path: 'programacion/ut2', component: IframeContentViewComponent },
  { path: 'programacion/ut3', component: IframeContentViewComponent },
  { path: 'programacion/ut4', component: IframeContentViewComponent },
  { path: 'programacion/ut5', component: IframeContentViewComponent },
  { path: 'programacion/ut6', component: IframeContentViewComponent },
  { path: 'programacion/ut7', component: IframeContentViewComponent },
  { path: 'programacion/ut8', component: IframeContentViewComponent },
  { path: 'programacion/ut9', component: IframeContentViewComponent },
  { path: 'programacion/ut10', component: IframeContentViewComponent },

  { path: 'sistemas-informaticos', component: HomeComponent},
  { path: 'sistemas-informaticos/ut1', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut2', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut3', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut4', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut5', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut6', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut7', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut8', component: IframeContentViewComponent },
  { path: 'sistemas-informaticos/ut9', component: IframeContentViewComponent },

  { path: 'bases-de-datos', component: HomeComponent},
  { path: 'bases-de-datos/ut1', component: IframeContentViewComponent },
  { path: 'bases-de-datos/ut2', component: IframeContentViewComponent },
  { path: 'bases-de-datos/ut3', component: IframeContentViewComponent },
  { path: 'bases-de-datos/ut4', component: IframeContentViewComponent },
  { path: 'bases-de-datos/ut5', component: IframeContentViewComponent },
  { path: 'bases-de-datos/ut6', component: IframeContentViewComponent },
  { path: 'bases-de-datos/ut7', component: IframeContentViewComponent },

  { path: 'lenguajes-de-marcas', component: HomeComponent},
  { path: 'lenguajes-de-marcas/ut1', component: IframeContentViewComponent },
  { path: 'lenguajes-de-marcas/ut2', component: IframeContentViewComponent },
  { path: 'lenguajes-de-marcas/ut3', component: IframeContentViewComponent },
  { path: 'lenguajes-de-marcas/ut4', component: IframeContentViewComponent },
  { path: 'lenguajes-de-marcas/ut5', component: IframeContentViewComponent },
  { path: 'lenguajes-de-marcas/ut6', component: IframeContentViewComponent },

  { path: 'development-environments', component: HomeComponent},
  { path: 'development-environments/ut1', component: IframeContentViewComponent },
  { path: 'development-environments/ut2', component: IframeContentViewComponent },
  { path: 'development-environments/ut3', component: IframeContentViewComponent },
  { path: 'development-environments/ut4', component: IframeContentViewComponent },
  { path: 'development-environments/ut5', component: IframeContentViewComponent },

  { path: 'training-and-job-guidance', component: HomeComponent},
  { path: 'training-and-job-guidance/ut1', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut2', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut3', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut4', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut5', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut6', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut7', component: IframeContentViewComponent },
  { path: 'training-and-job-guidance/ut8', component: IframeContentViewComponent },

  { path: 'client-side-web-development', component: HomeComponent},
  { path: 'client-side-web-development/ut1', component: IframeContentViewComponent },
  { path: 'client-side-web-development/ut2', component: IframeContentViewComponent },
  { path: 'client-side-web-development/ut3', component: IframeContentViewComponent },
  { path: 'client-side-web-development/ut4', component: IframeContentViewComponent },
  { path: 'client-side-web-development/ut5', component: IframeContentViewComponent },
  { path: 'client-side-web-development/ut6', component: IframeContentViewComponent },

  { path: 'client-side-web-server', component: HomeComponent},
  { path: 'client-side-web-server/ut1', component: IframeContentViewComponent },
  { path: 'client-side-web-server/ut2', component: IframeContentViewComponent },
  { path: 'client-side-web-server/ut3', component: IframeContentViewComponent },
  { path: 'client-side-web-server/ut4', component: IframeContentViewComponent },
  { path: 'client-side-web-server/ut5', component: IframeContentViewComponent },
  { path: 'client-side-web-server/ut6', component: IframeContentViewComponent },
  { path: 'client-side-web-server/ut7', component: IframeContentViewComponent },

  { path: 'web-application-deployment', component: HomeComponent},
  { path: 'web-application-deployment/ut1', component: IframeContentViewComponent },
  { path: 'web-application-deployment/ut2', component: IframeContentViewComponent },
  { path: 'web-application-deployment/ut3', component: IframeContentViewComponent },
  { path: 'web-application-deployment/ut4', component: IframeContentViewComponent },
  { path: 'web-application-deployment/ut5', component: IframeContentViewComponent },

  { path: 'web-interface-design', component: HomeComponent},
  { path: 'web-interface-design/ut1', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut2', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut3', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut4', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut5', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut6', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut7', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut8', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut9', component: IframeContentViewComponent },
  { path: 'web-interface-design/ut10', component: IframeContentViewComponent },

  { path: 'company-and-entrepreneurial-initiative', component: HomeComponent},
  { path: 'company-and-entrepreneurial-initiative/ut1', component: IframeContentViewComponent },
  { path: 'company-and-entrepreneurial-initiative/ut2', component: IframeContentViewComponent },
  { path: 'company-and-entrepreneurial-initiative/ut3', component: IframeContentViewComponent },
  { path: 'company-and-entrepreneurial-initiative/ut4', component: IframeContentViewComponent },
  { path: 'company-and-entrepreneurial-initiative/ut5', component: IframeContentViewComponent },
  { path: 'company-and-entrepreneurial-initiative/ut6', component: IframeContentViewComponent },
  { path: 'company-and-entrepreneurial-initiative/ut7', component: IframeContentViewComponent },

  { path: 'web-application-development-project', component: HomeComponent},
  { path: 'web-application-development-project/ut1', component: IframeContentViewComponent },

  { path: 'training-in-workplaces', component: HomeComponent},
  { path: 'training-in-workplaces/ut1', component: IframeContentViewComponent }

];
